version: "3"

services:
  api:
    build: .
    #ports:
      #- "8000:80"
    #environment:
      #- APP_NAME=other names
    volumes:
      - .:/app
    command: uvicorn server:app --reload --port 80 --host 0.0.0.0

  web:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #build: nginx/
    ports:
      - "8000:80"
    depends_on:
      - api

